FROM ghcr.io/mkandes/naked-docker:ubuntu-20.04-openmpi-4.0.5

LABEL APPLICATION_NAME='High-Performance Linpack (HPL)'
LABEL APPLICATION_VERSION='2.3'
LABEL APPLICATION_URL='https://www.netlib.org/benchmark/hpl'

LABEL AUTHOR_NAME='Marty Kandes'
LABEL AUTHOR_EMAIL='mkandes@sdsc.edu'

LABEL LAST_UPDATED='20220104'

SHELL ["/bin/bash", "-c"]

ENV MIRRORURL='http://us.archive.ubuntu.com/ubuntu'
ENV OSVERSION='focal'
ENV LC_ALL=C
ENV DEBIAN_FRONTEND='noninteractive'

RUN apt-get -y purge --auto-remove command-not-found

RUN apt-get update \
 && apt-get -y upgrade \
 && apt-get -y autoremove --purge \
 && apt-get -y clean \
 && rm -rf /var/lib/apt/lists/*

ENV OPENBLAS_REPO_URL='https://github.com/xianyi/OpenBLAS.git'
ENV OPENBLAS_VERSION='0.3.14'
ENV OPENBLAS_ROOT_DIR='/opt/openblas'
ENV OPENBLAS_INSTALL_DIR="${OPENBLAS_ROOT_DIR}/${OPENBLAS_VERSION}"
ENV OPENBLAS_USE_OPENMP=1
ENV OPENBLAS_DYNAMIC_ARCH=0
ENV OPENBLAS_TARGET_ARCH='HASWELL'
ENV OPENBLAS_MAX_NUM_THREADS=256

WORKDIR /tmp

RUN git clone "${OPENBLAS_REPO_URL}" \
 && cd OpenBLAS \
 && git checkout "v${OPENBLAS_VERSION}" \
 && if (( "${OPENBLAS_DYNAMIC_ARCH}" == 1 )); \
    then make FC='gfortran' BINARY=64 USE_OPENMP="${OPENBLAS_USE_OPENMP}" DYNAMIC_ARCH=1 NUM_THREADS="${OPENBLAS_MAX_NUM_THREADS}"; \
    else make FC='gfortran' BINARY=64 USE_OPENMP="${OPENBLAS_USE_OPENMP}" TARGET="${OPENBLAS_TARGET_ARCH}" NUM_THREADS="${OPENBLAS_MAX_NUM_THREADS}"; \
    fi \
 && make PREFIX="${OPENBLAS_INSTALL_DIR}" install \
 && cd /tmp \
 && rm -rf OpenBLAS

env LD_LIBRARY_PATH="${OPENBLAS_INSTALL_DIR}/lib:${LD_LIBRARY_PATH}"

WORKDIR /tmp

ENV HPL_ROOT_URL='http://www.netlib.org/benchmark/hpl'
ENV HPL_VERSION='2.3'
ENV HPL_ARCH='linux64'
ENV HPL_ROOT_DIR='/opt/hpl'
ENV HPL_INSTALL_DIR="${HPL_ROOT_DIR}/${HPL_VERSION}"

RUN wget "${HPL_ROOT_URL}/hpl-${HPL_VERSION}.tar.gz" \
 && tar -xf "hpl-${HPL_VERSION}.tar.gz" \
 && cd "hpl-${HPL_VERSION}/setup" \
 && source make_generic \
 && mv Make.UNKNOWN Make.linux64 \
 && sed -i 's|ARCH         = UNKNOWN|ARCH         = linux64|' Make.linux64 \
 && sed -i 's|TOPdir       = $(HOME)/hpl|TOPdir       = |' Make.linux64 \
 && sed -i "s|TOPdir       = |TOPdir       = /opt/hpl/${HPL_VERSION}|" Make.linux64 \
 && sed -i 's|MPdir        = |MPdir        = /opt/openmpi/4.0.5|' Make.linux64 \
 && sed -i 's|MPinc        = |MPinc        = -I$(MPdir)/include|' Make.linux64 \
 && sed -i 's|MPlib        = |MPlib        = $(MPdir)/lib/libmpi.so|' Make.linux64 \
 && sed -i "s|LAdir        = |LAdir        = /opt/openblas/${OPENBLAS_VERSION}|" Make.linux64 \
 && sed -i 's|LAinc        = |LAinc        = -I$(LAdir)/include|' Make.linux64 \
 && sed -i 's|LAlib        = -lblas|LAlib        = $(LAdir)/lib/libopenblas.a|' Make.linux64 \
 && sed -i 's|LINKER       = mpif77|LINKER       = mpicc|' Make.linux64 \
 && cp Make.linux64 ../ \
 && cd ../ \
 && export LDFLAGS="-L${OPENBLAS_INSTALL_DIR}/lib" \
 && ./configure --prefix="${HPL_INSTALL_DIR}" \
 && make arch='linux64' \
 && make install \
 && cd /tmp \
 && rm -rf "hpl-${HPL_VERSION}" \
 && rm "hpl-${HPL_VERSION}.tar.gz" \
 && updatedb

ENV PATH="${HPL_INSTALL_DIR}/bin:${PATH}"
